config/routes.rb
Rails.application.routes.draw do
  resources :indices
  devise_for :customers
  devise_for :payments
  devise_for :order_items
  devise_for :payment_methods
  devise_for :orders
  devise_for :products
  devise_for :categories
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Index is the root path
  resources :indices
  root "indices#index"

  # Resources
  resources :categories
  resources :products do
    post :add_to_cart, on: :member
    delete :remove_from_cart, on: :member
    put :update_quantity_cart, on: :member
    delete :clear_cart
  end
  resources :orders
  resources :order_items
  resources :payments
  resources :payment_methods
  resources :checkouts do
    get :index, to: "checkouts#index", as: :index
    post :create, to: "checkouts#create", as: :create
    get :success, to: "checkouts#success", as: :success
    get :cancel, to: "checkouts#cancel", as: :cancel
  end
  resources :customers
  resources :province_taxes

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  def index
    # if not logged in, redirect to login
    if !current_customer
      redirect_to new_customer_session_path
      return
    end

    # if cart is empty or doesn't exist, redirect to root
    if !session[:cart] || session[:cart].empty?
      redirect_to root_path
      return
    end

    @taxes = ProvinceTax.all
    
    #store selected province in session
    if params[:province]
      session[:province] = params[:province]
    elsif current_customer.province_tax_id
      session[:province] = ProvinceTax.find(current_customer.province_tax_id).name
      redirect_to checkouts_path(province: session[:province])
    end

    @tax = if session[:province] 
      ProvinceTax.find_by(name: session[:province])
    else
      session[:province] = ProvinceTax.first
    end

    if @tax
      # update user's province
      current_customer.province_tax_id = @tax.id
      current_customer.save
    end
  end

  def create
    line_items = []
    total_cents = 0

    session[:cart].each do |value|
        line_items << {
          price_data: {
            currency: 'cad',
            unit_amount: value[1]['product']['price_cents'],
            product_data: {
              name: value[1]['product']['name'],
              description: value[1]['product']['description']
            }
          },
          quantity: value[1]['quantity']
        }

        total_cents += value[1]['product']['price_cents'] * value[1]['quantity']
    end
    
    # Redirect if line items are empty
    if line_items.empty?
      redirect_to root_path
      return
    end

    # add tax to line items and total
    @tax = ProvinceTax.find_by(name: session[:province] || ProvinceTax.first.name)
    pst = (total_cents * @tax.pst).round
    gst = (total_cents * @tax.gst).round
    line_items << {
      price_data: {
        currency: 'cad',
        unit_amount: pst,
        product_data: {
          name: 'PST',
          description: 'Provincial Sales Tax'
        }
      },
      quantity: 1
    }
    line_items << {
      price_data: {
        currency: 'cad',
        unit_amount: gst,
        product_data: {
          name: 'GST',
          description: 'Goods and Services Tax'
        }
      },
      quantity: 1
    }

    total_cents += pst + gst

    # Create a new Stripe session
    @session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        line_items: line_items,
        mode: 'payment',
        success_url: checkout_success_url(1) + '?session_id={CHECKOUT_SESSION_ID}',
        cancel_url: checkout_cancel_url(1) + '?session_id={CHECKOUT_SESSION_ID}',
    )

    # Create a new Order if stripe_session_id doesn't exist
    @order = Order.find_by(stripe_session_id: @session.id)
    if @order == nil 
      @order = Order.create(
        status: 'pending',
        stripe_session_id: @session.id,
        total_price_cents: total_cents,
        customer_id: current_customer.id
      )
    end

    # Create order items
    line_items.each do |item|
      if item[:price_data][:product_data][:name] == 'PST' || item[:price_data][:product_data][:name] == 'GST'
        next
      end
      product = Product.find_by(name: item[:price_data][:product_data][:name])
      OrderItem.create(
        order_id: @order.id,
        product_id: product.id,
        quantity: item[:quantity],
        unit_price_cents: item[:price_data][:unit_amount]
      )
    end

    Order.create(status: 'pending', stripe_session_id: @session.id, total_price_cents: total_cents, customer_id: current_customer.id)

    puts @order

    # Redirect to Stripe checkout
    redirect_to @session.url, allow_other_host: true
  end

  def success
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)

    # Update the order
    @order = Order.find_by(stripe_session_id: @session.id)
    @order.status = 'paid'
    @order.total_price_cents = @payment_intent.amount
    @order.save

    # Clear the cart
    session[:cart] = {}
  end

  def cancel
    # Update the order
    @order = Order.find_by(stripe_session_id: params[:session_id])
    @order.status = 'cancelled'
    @order.save
  end
end

app/views/checkouts/cancel.html.erb
Boo....

Order canceled:
<%= @order.id %>
<%= @order.created_at.strftime("%B %d, %Y") %>
<%= @order.status %>
<%= number_to_currency(@order.total / 100) %>
<%= link_to 'Details', order %>

app/views/checkouts/index.html.erb
<h1>Your Order</h1>

<% subtotal = 0 %>

<% @cart.each do |item| %>
    <% product = item[1]['product'] %>
    <p><b><%= product['name'] %></b></p>
    <p><small><%= product['description'] %> </small></p>
    <p><%= number_to_currency(product['price_cents'] / 100) %> x <%= item[1]['quantity'] %> = <%= number_to_currency(product['price_cents'] * item[1]['quantity'] / 100) %></p>
    <hr>
    <% subtotal += product['price_cents'] * item[1]['quantity'] %>
<% end %>

<hr><hr>
<p><b>Subtotal:</b> <%= number_to_currency(subtotal / 100) %></p>
<p>
    <b>Province:</b>
    <select id="province">
        <% @taxes.each do |tax| %>
            <option value="<%= tax['name'] %>" data-gst="<%= tax['gst'] %>" data-pst="<%= tax['pst'] %>" <% if params[:province] == tax['name'] %> selected <% end %>>
                <%= tax['name'] %>
            </option>
        <% end %>
    </select>
</p>
<p><b>GST:</b> $<span id="gst"></span></p>
<p><b>PST:</b> $<span id="pst"></span></p>
<p><b>Total:</b> $<span id="total"></span> CAD</p>

<script>
    function calculateTotal() {
        const province = document.getElementById('province').value;
        const gst = document.querySelector(`option[value="${province}"]`).dataset.gst;
        const pst = document.querySelector(`option[value="${province}"]`).dataset.pst;
        const subtotal = <%= subtotal / 100 %>;
        const gstAmount = parseFloat(subtotal) * parseFloat(gst);
        const pstAmount = parseFloat(subtotal) * parseFloat(pst);
        const total = parseFloat(subtotal) + parseFloat(gstAmount) + parseFloat(pstAmount);
        document.getElementById('gst').innerHTML = gstAmount.toFixed(2);
        document.getElementById('pst').innerHTML = pstAmount.toFixed(2);
        document.getElementById('total').innerHTML = total.toFixed(2);
    }

    document.getElementById('province').addEventListener('change', function(event) {
        window.location.href = '?province=' + event.target.value;
        calculateTotal();
    });

    calculateTotal();
</script>

<%= button_to '💳 Buy Now', checkout_create_path(1), method: :post, class: 'btn btn-success', data: {turbo: false} %>

app/views/checkouts/success.html.erb
YAY!

See your order details below:
<%= @order.id %>
<%= @order.created_at.strftime("%B %d, %Y") %>
<%= @order.status %>
<%= number_to_currency(@order.total_price_cents / 100) %>
<%= link_to 'Details', @order %>