config/routes.rb
Rails.application.routes.draw do
  resources :indices
  devise_for :customers
  devise_for :payments
  devise_for :order_items
  devise_for :payment_methods
  devise_for :orders
  devise_for :products
  devise_for :categories
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Index is the root path
  resources :indices
  root "indices#index"

  # Resources
  resources :categories
  resources :products do
    post :add_to_cart, on: :member
    delete :remove_from_cart, on: :member
    put :update_quantity_cart, on: :member
    delete :clear_cart
  end
  resources :orders
  resources :order_items
  resources :payments
  resources :payment_methods
  resources :checkouts do
    get :index, to: "checkouts#index", as: :index
    post :create, to: "checkouts#create", as: :create
    get :success, to: "checkouts#success", as: :success
    get :cancel, to: "checkouts#cancel", as: :cancel
  end
  resources :customers
  resources :province_taxes

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :price_cents, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :image_url, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "description", "id", "id_value", "image_url", "name", "price_cents", "quantity", "updated_at"]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index_params
      params.require(:product).permit()
    end

    def index
        @products = ::Product.includes(:category).all
    end

    def show
        @product = ::Product.includes(:category).find(params[:id])
    end

    def add_to_cart
        product = ::Product.find(params[:id])
        session[:cart] ||= {}
        if session[:cart][product.name].present?
            session[:cart][product.name][:quantity] = session[:cart][product.name][:quantity].to_i + 1
        else
            session[:cart][product.name] = {
                quantity: 1,
                product: product
            }
        end
    end

    def remove_from_cart
        product = ::Product.find(params[:id])
        session[:cart].delete(product.name)
    end

    def checkout
        
    end

    def update_quantity_cart
        product = ::Product.find(params[:id])
        session[:cart][product.name]['quantity'] = params[:quantity].to_i
        if session[:cart][product.name]['quantity'] == 0
            session[:cart].delete(product.name)
        end
    end

    def clear_cart
        session[:cart] = {}
    end
end

app/views/products/_product.html.erb
<div class="card" style="margin-bottom: 20px;">
  <div class="card-header" >
    <%= link_to product.name, product %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= product.description %></h5>
    <p class="card-text"><%= number_to_currency(product.price_cents / 100) %></p>
    <%= button_to 'Add to cart', add_to_cart_product_path(product), method: :post, class: 'btn btn-dark', onclick: "refreshPage()" %>
  </div>
</div>

app/views/products/index.html.erb
<body style="background-color:black; ">
<h1 class="text-white">Products</h1>

<div class="col-12 text-white">
<div class="card text-white bg-secondary mb-3" style="max-width: 11rem;">
    <nav aria-label="breadcrumb">
  <ol class="breadcrumb card-text">
    <li class="breadcrumb-item card-text"><a href="<%= indices_path %>">Home</a></li>
    <li class="breadcrumb-item active card-text" aria-current="page">Products</li>
  </ol>
</nav>
  </div>
</div>
    <div class="row">
    <% @products.each do |product| %>
        <%= render partial: 'product', locals: { product: product } %>
    <% end %>
    </div>
</div>
</body>

app/views/products/show.html.erb
<body style="background-color:black;">
<div class="card text-white bg-secondary mb-3" style="max-width: 27rem; margin: 10px">
    <nav aria-label="breadcrumb">
  <ol class="breadcrumb card-text">
    <li class="breadcrumb-item card-text"><a href="<%= indices_path %>">Home</a></li>
    <li class="breadcrumb-item card-text"><a href="<%= products_path %>">Job Postings</a></li>
    <li class="breadcrumb-item active card-text" aria-current="page"><%= @product.name %></li>
  </ol>
</nav>
  </div>
<div class="card" style="margin: 20px;">
  <div class="card-header" >
<h1><%= @product.name %></h1>
</div>
<div class="card-body">
<p class="card-title"><%= @product.description %></p>
<p class="card-text"><%= number_to_currency(@product.price_cents / 100) %></p>
<%= button_to 'Add to cart', add_to_cart_product_path(@product), method: :post, class: 'btn btn-primary text-light', onclick: "refreshPage()" %>
</div>
</body>