config/routes.rb
Rails.application.routes.draw do
  resources :indices
  devise_for :customers
  devise_for :payments
  devise_for :order_items
  devise_for :payment_methods
  devise_for :orders
  devise_for :products
  devise_for :categories
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Index is the root path
  resources :indices
  root "indices#index"

  # Resources
  resources :categories
  resources :products do
    post :add_to_cart, on: :member
    delete :remove_from_cart, on: :member
    put :update_quantity_cart, on: :member
    delete :clear_cart
  end
  resources :orders
  resources :order_items
  resources :payments
  resources :payment_methods
  resources :checkouts do
    get :index, to: "checkouts#index", as: :index
    post :create, to: "checkouts#create", as: :create
    get :success, to: "checkouts#success", as: :success
    get :cancel, to: "checkouts#cancel", as: :cancel
  end
  resources :customers
  resources :province_taxes

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LD Careers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/css/bootstrap.min.css" integrity="sha512-b2QcS5SsA8tZodcDtGRELiGv5SaKSk1vDHDaQRda0htPYWZ6046lr3kJ5bAAQdpV2mmA/4v0wQF9MyU6/pDIAg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/js/bootstrap.bundle.min.js" integrity="sha512-X/YkDZyjTf4wyc2Vy16YGCPHwAY8rZJY+POgokZjQB2mhIRFJCckEGc6YyX9eNsPfn0PzThEuNs+uaomE5CO6A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <script>
      function refreshPage() {
        setTimeout(() => {
          location.reload();
        }, 1000);
      }
    </script>
  </head>

  <body>
    <p style="color: green"><%= notice %></p>

    <nav class="navbar bg-dark border-bottom border-body">
      <div class="container-fluid">
        <a class="navbar-brand" style="color: white"><%= @store_info['name'] %></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <% if current_customer %>
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <%= current_customer.email %>
                </a>
                <%= link_to 'Edit Profile', edit_customer_registration_path, class: 'dropdown-item' %>
                <%= button_to 'Logout', destroy_customer_session_path, method: :delete, class: 'dropdown-item' %>
              <% else %>
                  <%= link_to 'Login', new_customer_session_path, class: 'dropdown-item' %>
                  <%= link_to 'Register', new_customer_registration_path, class: 'dropdown-item' %>
              <% end %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Cart : <%= @cart.count %> item(s)
              </a>
              <ul class="dropdown-menu">
                <% if @cart.present? && @cart.count > 0 %>
                  
                <% else %>
                  <li>Cart is empty!</li>
                <% end %>
                <li><hr class="dropdown-divider"></li>
                <li><hr class="dropdown-divider"></li>
                <% @cart.each do |item| %>
                  <li class="d-flex justify-content-between align-items-center">
                    <%= link_to item[0], product_path(item[1]['product']['id']), class: 'dropdown-item' %>
                    : 
                    <%= form_tag update_quantity_cart_product_path(item[1]['product']['id']), method: :put do %>
                      <%= hidden_field_tag :product_id, item[1]['product']['id'] %>
                      <%= number_field_tag 'quantity', item[1]['quantity'], min: 1 %>
                      <%= submit_tag 'Update', onclick: "refreshPage()" %>
                    <% end %>
                    <%= button_to '❌', remove_from_cart_product_path(item[1]['product']['id']), method: :delete, class: 'btn btn-danger', onclick: "refreshPage()" %>
                  </li>
                  <li><hr class="dropdown-divider"></li>
                <% end %>
                <li><hr class="dropdown-divider"></li>
                <li><hr class="dropdown-divider"></li>
                <% if @cart.present? && @cart.count > 0 %>
                  <li><%= link_to 'Checkout', checkouts_path, class: 'dropdown-item' %></li>
                <% end %>
              </ul>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" id="q" value="<%= params[:search] %>">
            <select class="form-select" aria-label="Default select example" id="category" name="category">
              <option <% if  params[:category].blank? %> selected <% end %>>All Categories</option>
              <% @categories.each do |category| %>
                <option value="<%= category.name %>" <% if params[:category] == category.name.to_s %> selected <% end %>><%= category.name %></option>
              <% end %>
            </select>
            <button class="btn btn-outline-light" type="submit" id="searchbtn">Search Products</button>
            <script>
              function handleSearch(event) {
                event.preventDefault();
                const query = document.getElementById('q').value;
                const category = document.getElementById('category').value;
                if (query.length > 0){
                  if (category.length > 0) {
                    window.location.href = '/?search=' + query + '&category=' + category;
                  } else {
                    window.location.href = '/?search=' + query;
                  }
                }
              }

              document.getElementById('q').addEventListener('keyup', function(event) {
                if (event.key === 'Enter') {
                  handleSearch(event);
                }
              });

              document.getElementById('searchbtn').addEventListener('click', function(event) {
                handleSearch(event);
              });

              document.getElementById('category').addEventListener('change', function(event) {
                handleSearch(event);
              });
            </script>
          </form>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>